[technote]
id = "SITCOMTN-123"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-123.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-123"
github_default_branch = "main"
date_created = 2024-04-03T13:19:41Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Laura"
name.family = "Toribio San Cipriano"
internal_id = "toribiol"

[[technote.authors.affiliations]]
name = "Centro de Investigaciones Energéticas"
internal_id = "CIEMAT"
address = "Medioambientales y Tecnológicas, Av. Complutense 40, 28040 Madrid, Spain"
